---
- name: install zip
  apt:
    name: zip
    state: present

- name: clone wazuh app repo
  git:
    repo: https://github.com/wazuh/wazuh-kibana-app
    dest: /tmp/kibana/wazuh

- name: zip wazuh app
  shell: cd /tmp/ && zip -r /tmp/kibana.zip kibana


- name: install wazuh dashboard plugin
  command: /usr/share/kibana/bin/kibana-plugin remove wazuh
  args:
    creates: /usr/share/kibana/plugins/wazuh
  notify: restart kibana

- name: install wazuh dashboard plugin
  command: /usr/share/kibana/bin/kibana-plugin install file:///tmp/kibana.zip
  args:
    creates: /usr/share/kibana/plugins/wazuh
  notify: restart kibana
